### ISSUE TITLE
Question about method dgl.metis_partition while doing REG partition.

### ISSUE THREAD

**Issue by RichardLoveMP** [HaibaraAiChan/Betty#3]
Dear Author,
     I have read this paper and your REG Partitioning method is quite impressive. I noticed you are using the function "dgl.metis_partition" to partition the REG graph whose weight is the product of the adjacency matrix A and its transpose A_T. I have read the tutorial and code of DGL about this function, but the document only mentions balancing the number of nodes and edges instead of balancing edge weight. 
     Therefore, I wonder if I understand your partition algorithm correctly and precisely. Could you help me with my confusion?

Thank you!

**Comment by HaibaraAiChan** [comment]
Based on the doc of DGL and my experimental results, dgl.metis only support unweight graph now.  If you want to do weighted graph, you can find in [dgl discussion](https://discuss.dgl.ai/t/efficient-graph-partition-using-edge-attribute/503)"One possibility is to use an existing library [metis 6](https://pdfs.semanticscholar.org/b82d/b3ddeac318e18b09035243ecbd516b7acfe8.pdf) to partition graphs based on edge weights using NetworkX graphs."
Hope this can help you.

**Comment by RichardLoveMP** [comment]
Thanks for your prompt feedback. I am sorry that I am still a little bit confused about one point.
Does METIS in REG partition algorithm (Algorithm 1 Line 8 in this paper) consider the edge weight of REG?

Many thanks for your assistance in advance.

**Comment by HaibaraAiChan** [comment]
The REG partition algorithm doesn't consider the edge weights of REG. As most of the nodes share no neighbor or just one neighbor with others in real large graph data, (most of the input graphs are sparse).  Based on the results of the experiments tested on the datasets mentioned in the paper, the weight of REG edges has no possitive effect on the partition result.

**Comment by RichardLoveMP** [comment]
I see. Thank you for your clear explanation. 🤝
